Fix FTBFS on GNU/kFreeBSD due to an undefined reference to __bswap32. Bug-Debian: http://bugs.debian.org/566776
git-svn-id: svn://svn.code.sf.net/p/freeassociation/code/trunk@991 b29e25b1-4845-0410-9c6e-9608a45a5811